In [1]:
import pandas as pd
import os 
import numpy as np

In [2]:
print(os.getcwd())

/Users/ruturajdesai/Desktop/Data-Science/projects/end_to_end/flight_prediction/notebooks

In [3]:
os.chdir('../') 

print(os.getcwd())

/Users/ruturajdesai/Desktop/Data-Science/projects/end_to_end/flight_prediction

In [30]:
X_train = pd.read_csv(os.path.join("data", "splitted_data", "X_train.csv"))
y_train = pd.read_csv(os.path.join("data", "splitted_data", "y_train.csv"))
X_test= pd.read_csv(os.path.join("data","splitted_data","X_test.csv"))
y_test=pd.read_csv(os.path.join("data","splitted_data","y_test.csv"))
x_val=pd.read_csv(os.path.join("data","splitted_data","X_val.csv"))
y_val=pd.read_csv(os.path.join("data","splitted_data","y_val.csv"))

In [31]:
X_train[X_train.isnull().any(axis=1)]

Empty DataFrame
Columns: [airline, source_city, destination_city, duration, total_stops, additional_info, arrival_hr, arrival_min, flight_day, flight_month, dep_hr, dep_min, day_of_week, is_weekend]
Index: []

In [32]:
X_train[X_train['total_stops'].isnull()]

Empty DataFrame
Columns: [airline, source_city, destination_city, duration, total_stops, additional_info, arrival_hr, arrival_min, flight_day, flight_month, dep_hr, dep_min, day_of_week, is_weekend]
Index: []

In [33]:
df=pd.read_csv(os.path.join("data", "raw", "flight_price.csv"))

In [34]:
df.head()

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
0,IndiGo,24/03/2019,Banglore,New Delhi,BLR → DEL,22:20,01:10 22 Mar,2h 50m,non-stop,No info,3897
1,Air India,1/05/2019,Kolkata,Banglore,CCU → IXR → BBI → BLR,05:50,13:15,7h 25m,2 stops,No info,7662
2,Jet Airways,9/06/2019,Delhi,Cochin,DEL → LKO → BOM → COK,09:25,04:25 10 Jun,19h,2 stops,No info,13882
3,IndiGo,12/05/2019,Kolkata,Banglore,CCU → NAG → BLR,18:05,23:30,5h 25m,1 stop,No info,6218
4,IndiGo,01/03/2019,Banglore,New Delhi,BLR → NAG → DEL,16:50,21:35,4h 45m,1 stop,No info,13302

In [35]:
df[df['Total_Stops'].isnull()]

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
9039,Air India,6/05/2019,Delhi,Cochin,NaN,09:45,09:25 07 May,23h 40m,NaN,No info,7480

In [36]:
df[df.isnull().any(axis=1)]

,Airline,Date_of_Journey,Source,Destination,Route,Dep_Time,Arrival_Time,Duration,Total_Stops,Additional_Info,Price
9039,Air India,6/05/2019,Delhi,Cochin,NaN,09:45,09:25 07 May,23h 40m,NaN,No info,7480

In [37]:
df['Total_Stops'].value_counts(dropna=False)

Total_Stops
1 stop      5625
non-stop    3491
2 stops     1520
3 stops       45
NaN            1
4 stops        1
Name: count, dtype: int64