In [26]:

import pandas as pd
import os 
import numpy as np

In [27]:
print(os.getcwd())

/Users/ruturajdesai/Desktop/Data-Science/projects/end_to_end/flight_prediction

In [28]:
os.chdir('../') 

print(os.getcwd())

/Users/ruturajdesai/Desktop/Data-Science/projects/end_to_end

In [ ]:
X_train = pd.read_csv(os.path.join("data", "splitted_data", "X_train.csv"))
y_train = pd.read_csv(os.path.join("data", "splitted_data", "y_train.csv"))
X_test= pd.read_csv(os.path.join("data","splitted_data","X_test.csv"))
y_test=pd.read_csv(os.path.join("data","splitted_data","y_test.csv"))
x_val=pd.read_csv(os.path.join("data","splitted_data","X_val.csv"))
y_val=pd.read_csv(os.path.join("data","splitted_data","y_val.csv"))

FileNotFoundError: [Errno 2] No such file or directory: 'data/splitted_data/X_train.csv'

In [14]:
X_train[X_train.isnull()=="True"]

,airline,source_city,destination_city,duration,total_stops,additional_info,arrival_hr,arrival_min,flight_day,flight_month,dep_hr,dep_min,day_of_week,is_weekend
0,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
1,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
2,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
3,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
4,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
6831,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6832,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6833,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6834,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN
6835,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN,NaN

In [17]:
X_train[X_train['airline'].isnull()]

Empty DataFrame
Columns: [airline, source_city, destination_city, duration, total_stops, additional_info, arrival_hr, arrival_min, flight_day, flight_month, dep_hr, dep_min, day_of_week, is_weekend]
Index: []

In [22]:
X_train[X_train.isnull().any(axis=1)]

,airline,source_city,destination_city,duration,total_stops,additional_info,arrival_hr,arrival_min,flight_day,flight_month,dep_hr,dep_min,day_of_week,is_weekend
119,air india,delhi,cochin,1420.0,NaN,No info,9,25,6,5,9,45,0,0

In [19]:
X_train['total_stops'].value_counts()

total_stops
1.0    3603
0.0    2240
2.0     964
3.0      28
Name: count, dtype: int64

In [25]:
X_test[X_test.isnull().any(axis=1)]

Empty DataFrame
Columns: [airline, source_city, destination_city, duration, total_stops, additional_info, arrival_hr, arrival_min, flight_day, flight_month, dep_hr, dep_min, day_of_week, is_weekend]
Index: []